# Generated by Django 5.1.3 on 2024-12-11 07:44

import django.db.models.deletion
import oreo.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=oreo.models.user_main_photo_path)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=oreo.models.user_sub_photo_path)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('main_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_photos', to='oreo.mainphoto')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=50, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=20, null=True)),
                ('kakao_id', models.CharField(max_length=50, null=True, unique=True)),
                ('urls', models.JSONField(default=list)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_photos', to='oreo.userprofile'),
        ),
    ]
