# Generated by Django 5.1.3 on 2024-12-10 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='main_photos/')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=50, unique=True)),
                ('real_name', models.CharField(blank=True, max_length=20, null=True)),
                ('kakao_id', models.CharField(max_length=50, null=True, unique=True)),
                ('urls', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SubPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='sub_photos/')),
                ('text', models.TextField(blank=True, null=True)),
                ('main_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_photos', to='oreo.mainphoto')),
            ],
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_photos', to='oreo.userprofile'),
        ),
    ]
