# Generated by Django 5.1.3 on 2024-11-25 12:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='main_photos/')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=50)),
                ('real_name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message='전화번호는 9자리에서 15자리 숫자로 입력해야 합니다.', regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='SubPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='sub_photos/')),
                ('text', models.TextField(blank=True, null=True)),
                ('main_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_photos', to='oreo.mainphoto')),
            ],
        ),
        migrations.AddField(
            model_name='mainphoto',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_photos', to='oreo.userprofile'),
        ),
    ]
