# Generated by Django 5.1.3 on 2024-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oreo', '0002_remove_userprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
    ]
